/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package component;


import java.awt.event.ActionListener;

/**
 *
 * @author Yusuf
 */

public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
    }

    public void addEventLogin(ActionListener event){
        toLogin.addActionListener(event);
    }
    
    public void addEventAfterRegister(ActionListener event){
        register.addActionListener(event);
    }
    
//    @Override
    public String getNameRegister(){
        return nameRegister.getText();
    }
    
    public String getUsername(){
        return usernameRegister.getText();
    }
    
    public String getPassword(){
        char[] password = passwordRegister.getPassword();
        String passToStr = new String(password);
        
        return passToStr;
    }
    
    public String getGender(){
        return (String)genderRegister.getSelectedItem();
    }
    
    public void resetForm() {
        nameRegister.setText("");
        usernameRegister.setText("");
        passwordRegister.setText("");
        genderRegister.setSelectedIndex(-1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new customSwing.PanelRound();
        usernameRegister = new customSwing.TextField();
        passwordRegister = new customSwing.PasswordField();
        register = new customSwing.Button();
        jLabel1 = new javax.swing.JLabel();
        toLogin = new customSwing.Link();
        nameRegister = new customSwing.TextField();
        genderRegister = new customSwing.Combobox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 253, 253));
        setOpaque(false);
        setLayout(null);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(80);
        panelRound1.setRoundTopRight(80);

        usernameRegister.setLabelText("Username");

        passwordRegister.setLabelText("Password");

        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.setRadius(29);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("already have an account?");

        toLogin.setText("login here");
        toLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        toLogin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        toLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLoginActionPerformed(evt);
            }
        });

        nameRegister.setLabelText("Name");
        nameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRegisterActionPerformed(evt);
            }
        });

        genderRegister.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        genderRegister.setSelectedIndex(-1);
        genderRegister.setLabeText("Gender");
        genderRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(usernameRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(register, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(nameRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(nameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(toLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        add(panelRound1);
        panelRound1.setBounds(60, 180, 292, 380);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setText("Boarding House Apps!");
        add(jLabel2);
        jLabel2.setBounds(60, 120, 260, 30);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel3.setText("Welcome to");
        add(jLabel3);
        jLabel3.setBounds(60, 90, 140, 30);

        background.setIcon(new javax.swing.ImageIcon("D:\\Coding\\NetBeansProjects\\Dormitory\\picture\\Amazing Girl (just_amazinggirl) on Pinterest.jpg")); // NOI18N
        add(background);
        background.setBounds(0, 0, 420, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void toLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toLoginActionPerformed

    private void nameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRegisterActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_registerActionPerformed

    private void genderRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderRegisterActionPerformed
        // TODO add your handling code here:
//        String option = (String)genderRegister.getSelectedItem();
//        
//        if(option.equals("Gender")){
////            if(isUpdate == true){
//                // Disable Top Item in ComboBox
//                System.out.println("[WARNING] Unable to use this item!");
//                JOptionPane.showMessageDialog(null, "Harap masukkan input yang valid di bagian gender!");
//                resetForm();
////                btnAdd.setText("Add");
////                btnDelete.setVisible(false);
////                this.isUpdate = false;
////            }
//        }else{
//            genderRegister.setSelectedItem(String.valueOf(option));
//        }
    }//GEN-LAST:event_genderRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private customSwing.Combobox genderRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private customSwing.TextField nameRegister;
    private customSwing.PanelRound panelRound1;
    private customSwing.PasswordField passwordRegister;
    private customSwing.Button register;
    private customSwing.Link toLogin;
    private customSwing.TextField usernameRegister;
    // End of variables declaration//GEN-END:variables
}
